[tox]
minversion = 4.6.3
env_list = mypy, pylint, black, isort

[testenv:mypy]
description = run type checks
deps =
    mypy
    pandas-stubs
commands = mypy {posargs:src}

[testenv:pylint]
description = run linters
deps = pylint
commands = pylint {posargs:src}

[testenv:black]
description = run code formatters
skip_install = true
deps = black[jupyter]
commands = black {posargs:.}

[testenv:isort]
description = run import formatters
skip_install = true
deps = isort
commands = isort {posargs:.}
