[tox]
minversion = 4.6.3
env_list = 3.1{0,1,2}, mypy, pylint, black, isort

[testenv]
description = run tests
deps = -r test/requirements.txt
commands = python -m pytest {posargs:.}

[testenv:mypy]
description = run type checks
basepython = 3.10
deps =
    mypy
    pandas-stubs
commands = python -m mypy {posargs:src test}

[testenv:pylint]
description = run linters
basepython = 3.10
deps = pylint
commands = python -m pylint {posargs:src test}

[testenv:black]
description = run code formatters
skip_install = true
deps = black[jupyter]
commands = python -m black {posargs:.}

[testenv:isort]
description = run import formatters
skip_install = true
deps = isort
commands = python -m isort {posargs:.}
